### Подготовил: Чичкина О.К.
### Студ. билет: 1032217621

### Кортежи

#### Примеры кортежей:

In [1]:
# пустой кортеж:
()

()

In [2]:
# кортеж из элементов типа String:
favoritelang = ("Python","Julia","R")

("Python", "Julia", "R")

In [3]:
# кортеж из целых чисел:
x1 = (1, 2, 3)


(1, 2, 3)

In [4]:
# кортеж из элементов разных типов:
x2 = (1, 2.0, "tmp")


(1, 2.0, "tmp")

In [5]:
# именованный кортеж:
x3 = (a=2, b=1+2)

(a = 2, b = 3)

#### Примеры операций над кортежами:

In [6]:
# длина кортежа x2:
length(x2)

3

In [7]:
# обратиться к элементам кортежа x2:
x2[1], x2[2], x2[3]


(1, 2.0, "tmp")

In [8]:
# произвести какую-либо операцию (сложение)
# с вторым и третьим элементами кортежа x1:
с = x1[2] + x1[3]

5

In [9]:
# обращение к элементам именованного кортежа x3:
x3.a, x3.b, x3[2]

(2, 3, 3)

In [10]:
# проверка вхождения элементов tmp и 0 в кортеж x2
# (два способа обращения к методу in()):
in("tmp", x2), 0 in x2

(true, false)

### Словари

#### Примеры словарей и операций над ними:

In [11]:
# создать словарь с именем phonebook:
phonebook = Dict("Иванов И.И." => ("867-5309","333-5544"),"Бухгалтерия" => "555-2368")

Dict{String, Any} with 2 entries:
  "Бухгалтерия" => "555-2368"
  "Иванов И.И." => ("867-5309", "333-5544")

In [12]:
# вывести ключи словаря:
keys(phonebook)

KeySet for a Dict{String, Any} with 2 entries. Keys:
  "Бухгалтерия"
  "Иванов И.И."

In [13]:
# вывести значения элементов словаря:
values(phonebook)

ValueIterator for a Dict{String, Any} with 2 entries. Values:
  "555-2368"
  ("867-5309", "333-5544")

In [14]:
# вывести заданные в словаре пары "ключ - значение":
pairs(phonebook)

Dict{String, Any} with 2 entries:
  "Бухгалтерия" => "555-2368"
  "Иванов И.И." => ("867-5309", "333-5544")

In [15]:
# проверка вхождения ключа в словарь:
haskey(phonebook, "Иванов И.И.")

true

In [16]:
# добавить элемент в словарь:
phonebook["Сидоров П.С."] = "555-3344"

"555-3344"

In [17]:
# удалить ключ и связанные с ним значения из словаря
pop!(phonebook, "Иванов И.И.")

("867-5309", "333-5544")

In [18]:
# Объединение словарей (функция merge()):
a = Dict("foo" => 0.0, "bar" => 42.0);
b = Dict("baz" => 17, "bar" => 13.0);
merge(a, b), merge(b,a)

(Dict{String, Real}("bar" => 13.0, "baz" => 17, "foo" => 0.0), Dict{String, Real}("bar" => 42.0, "baz" => 17, "foo" => 0.0))

### Множества

### Примеры множеств и операций над ними:

In [19]:
# создать множество из четырёх целочисленных значений:
A = Set([1, 3, 4, 5])

Set{Int64} with 4 elements:
  5
  4
  3
  1

In [20]:
# создать множество из 11 символьных значений:
B = Set("abrakadabra")

Set{Char} with 5 elements:
  'a'
  'd'
  'r'
  'k'
  'b'

In [21]:
# проверка эквивалентности двух множеств:
S1 = Set([1,2]);
S2 = Set([3,4]);
issetequal(S1,S2)

false

In [22]:
S3 = Set([1,2,2,3,1,2,3,2,1]);
S4 = Set([2,3,1]);
issetequal(S3,S4)

true

In [23]:
# объединение множеств:
C=union(S1,S2)

Set{Int64} with 4 elements:
  4
  2
  3
  1

In [24]:
# пересечение множеств:
D = intersect(S1,S3)

Set{Int64} with 2 elements:
  2
  1

In [25]:
# разность множеств:
E = setdiff(S3,S1)

Set{Int64} with 1 element:
  3

In [26]:
# проверка вхождения элементов одного множества в другое:
issubset(S1,S4)

true

In [27]:
# добавление элемента в множество:
push!(S4, 99)

Set{Int64} with 4 elements:
  2
  99
  3
  1

In [28]:
# удаление последнего элемента множества:
pop!(S4)

2

### Массивы

#### Примеры массивов:

In [29]:
# создание пустого массива с абстрактным типом:
empty_array_1 = []

Any[]

In [30]:
# создание пустого массива с конкретным типом:
empty_array_2 = (Int64)[]
empty_array_3 = (Float64)[]

Float64[]

In [31]:
# вектор-столбец:
a = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [32]:
# вектор-строка:
b = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [33]:
# многомерные массивы (матрицы):
A = [[1, 2, 3] [4, 5, 6] [7, 8, 9]]
B = [[1 2 3]; [4 5 6]; [7 8 9]]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [34]:
# одномерный массив из 8 элементов (массив $1 \times 8$)
# со значениями, случайно распределёнными на интервале [0, 1):
c = rand(1,8)

1×8 Matrix{Float64}:
 0.553591  0.833089  0.0517456  0.967074  …  0.513059  0.579578  0.109872

In [35]:
# многомерный массив $2 \times 3$ (2 строки, 3 столбца) элементов
# со значениями, случайно распределёнными на интервале [0, 1):
C = rand(2,3)

2×3 Matrix{Float64}:
 0.0876047  0.500629  0.0141571
 0.0666232  0.373311  0.0281683

In [36]:
# трёхмерный массив:
D = rand(4, 3, 2)

4×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.424369   0.798456  0.539386
 0.0647297  0.418553  0.00960523
 0.0851404  0.583136  0.0750238
 0.211211   0.618672  0.711608

[:, :, 2] =
 0.674761  0.721877   0.379231
 0.78567   0.0551843  0.0497611
 0.772375  0.897268   0.941991
 0.488873  0.880433   0.616615

#### Примеры массивов, заданных некоторыми функциями через включение:

In [37]:
# массив из квадратных корней всех целых чисел от 1 до 10:
roots = [sqrt(i) for i in 1:10]

10-element Vector{Float64}:
 1.0
 1.4142135623730951
 1.7320508075688772
 2.0
 2.23606797749979
 2.449489742783178
 2.6457513110645907
 2.8284271247461903
 3.0
 3.1622776601683795

In [38]:
# массив с элементами вида 3*x^2,
# где x - нечётное число от 1 до 9 (включительно
ar_1 = [3*i^2 for i in 1:2:9]

5-element Vector{Int64}:
   3
  27
  75
 147
 243

In [39]:
# массив квадратов элементов, если квадрат не делится на 5 или 4:
ar_2=[i^2 for i=1:10 if (i^2%5!=0 && i^2%4!=0)]

4-element Vector{Int64}:
  1
  9
 49
 81

#### Некоторые операции для работы с массивами:

In [40]:
# одномерный массив из пяти единиц:
ones(5)

5-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0

In [41]:
# двумерный массив 2x3 из единиц:
ones(2,3)

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [42]:
# одномерный массив из 4 нулей:
zeros(4)

4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0

In [43]:
# заполнить массив 3x2 цифрами 3.5
fill(3.5,(3,2))

3×2 Matrix{Float64}:
 3.5  3.5
 3.5  3.5
 3.5  3.5

In [44]:
# заполнение массива посредством функции repeat():
repeat([1,2],3,3)
repeat([1 2],3,3)

3×6 Matrix{Int64}:
 1  2  1  2  1  2
 1  2  1  2  1  2
 1  2  1  2  1  2

In [45]:
# преобразование одномерного массива из целых чисел от 1 до 12
# в двумерный массив 2x6
a = collect(1:12)
b = reshape(a,(2,6))

2×6 Matrix{Int64}:
 1  3  5  7   9  11
 2  4  6  8  10  12

In [46]:
# транспонирование
b'

6×2 adjoint(::Matrix{Int64}) with eltype Int64:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [47]:
# транспонирование
с = transpose(b)

6×2 transpose(::Matrix{Int64}) with eltype Int64:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [48]:
# массив 10x5 целых чисел в диапазоне [10, 20]:
ar = rand(10:20, 10, 5)

10×5 Matrix{Int64}:
 14  19  15  19  11
 18  12  19  17  12
 19  17  16  10  19
 17  12  12  20  18
 17  11  11  12  10
 10  18  19  14  15
 16  12  16  11  10
 13  16  13  15  17
 16  16  18  12  18
 15  10  13  11  11

In [49]:
# выбор всех значений строки в столбце 2:
ar[:, 2]

10-element Vector{Int64}:
 19
 12
 17
 12
 11
 18
 12
 16
 16
 10

In [50]:
# выбор всех значений в столбцах 2 и 5:
ar[:, [2, 5]]

10×2 Matrix{Int64}:
 19  11
 12  12
 17  19
 12  18
 11  10
 18  15
 12  10
 16  17
 16  18
 10  11

In [51]:
# все значения строк в столбцах 2, 3 и 4:
ar[:, 2:4]

10×3 Matrix{Int64}:
 19  15  19
 12  19  17
 17  16  10
 12  12  20
 11  11  12
 18  19  14
 12  16  11
 16  13  15
 16  18  12
 10  13  11

In [52]:
# значения в строках 2, 4, 6 и в столбцах 1 и 5:
ar[[2, 4, 6], [1, 5]]

3×2 Matrix{Int64}:
 18  12
 17  18
 10  15

In [53]:
# значения в строке 1 от столбца 3 до последнего столбца:
ar[1, 3:end]

3-element Vector{Int64}:
 15
 19
 11

In [54]:
# сортировка по столбцам:
sort(ar,dims=1)

10×5 Matrix{Int64}:
 10  10  11  10  10
 13  11  12  11  10
 14  12  13  11  11
 15  12  13  12  11
 16  12  15  12  12
 16  16  16  14  15
 17  16  16  15  17
 17  17  18  17  18
 18  18  19  19  18
 19  19  19  20  19

In [55]:
# сортировка по строкам:
sort(ar,dims=2)

10×5 Matrix{Int64}:
 11  14  15  19  19
 12  12  17  18  19
 10  16  17  19  19
 12  12  17  18  20
 10  11  11  12  17
 10  14  15  18  19
 10  11  12  16  16
 13  13  15  16  17
 12  16  16  18  18
 10  11  11  13  15

In [56]:
# поэлементное сравнение с числом
# (результат - массив логических значений):
ar .> 14

10×5 BitMatrix:
 0  1  1  1  0
 1  0  1  1  0
 1  1  1  0  1
 1  0  0  1  1
 1  0  0  0  0
 0  1  1  0  1
 1  0  1  0  0
 0  1  0  1  1
 1  1  1  0  1
 1  0  0  0  0

In [57]:
# возврат индексов элементов массива, удовлетворяющих условию:
findall(ar .> 14)

27-element Vector{CartesianIndex{2}}:
 CartesianIndex(2, 1)
 CartesianIndex(3, 1)
 CartesianIndex(4, 1)
 CartesianIndex(5, 1)
 CartesianIndex(7, 1)
 CartesianIndex(9, 1)
 CartesianIndex(10, 1)
 CartesianIndex(1, 2)
 CartesianIndex(3, 2)
 CartesianIndex(6, 2)
 CartesianIndex(8, 2)
 CartesianIndex(9, 2)
 CartesianIndex(1, 3)
 ⋮
 CartesianIndex(6, 3)
 CartesianIndex(7, 3)
 CartesianIndex(9, 3)
 CartesianIndex(1, 4)
 CartesianIndex(2, 4)
 CartesianIndex(4, 4)
 CartesianIndex(8, 4)
 CartesianIndex(3, 5)
 CartesianIndex(4, 5)
 CartesianIndex(6, 5)
 CartesianIndex(8, 5)
 CartesianIndex(9, 5)

### Самостоятельное выполнение

#### №1. Даны множества: 𝐴 = {0, 3, 4, 9}, 𝐵 = {1, 3, 4, 7}, 𝐶 = {0, 1, 2, 4, 7, 8, 9}. Найти 𝑃 = 𝐴 ∩ 𝐵 ∪ 𝐴 ∩ 𝐵 ∪ 𝐴 ∩ 𝐶 ∪ 𝐵 ∩ 𝐶.

In [58]:
A = Set([0, 3, 4, 9])
B = Set([1, 3, 4, 7])
C = Set([0, 1, 2, 4, 7, 8, 9])

P = union(intersect(A, B), intersect(A, C), intersect(B, C))
println(P)

Set([0, 4, 7, 9, 3, 1])


#### №2. Приведите свои примеры с выполнением операций над множествами элементов разных типов.

In [59]:
# Пример 1: множество строк
set1 = Set(["apple", "banana", "cherry"])
set2 = Set(["banana", "cherry", "date"])
intersection = intersect(set1, set2)
println(intersection)

Set(["cherry", "banana"])


In [60]:
# Пример 2: множество чисел
set3 = Set([10, 20, 30])
set4 = Set([20, 40, 50])
difference = setdiff(set3, set4)
println(difference)

Set([10, 30])


#### №3. Создайте разными способами:

##### 3.1) массив (1, 2, 3, … 𝑁 − 1, 𝑁 ), 𝑁 выберите больше 20

In [61]:
N = 25
array1 = collect(1:N)
println(array1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]


##### 3.2) массив (𝑁, 𝑁 − 1 … , 2, 1), 𝑁 выберите больше 20

In [62]:
array2 = collect(N:-1:1)
println(array2)

[25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


##### 3.3) массив (1, 2, 3, … , 𝑁 − 1, 𝑁, 𝑁 − 1, … , 2, 1), 𝑁 выберите больше 20

In [63]:
array3 = vcat(collect(1:N), collect(N-1:-1:1))
println(array3)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


##### 3.4) массив с именем tmp вида (4, 6, 3)

In [64]:
tmp = [4, 6, 3]
println(tmp)

[4, 6, 3]


##### 3.5) массив, в котором первый элемент массива tmp повторяется 10 раз

In [65]:
array4 = fill(tmp[1], 10)
println(array4)

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4]


##### 3.6) массив, в котором все элементы массива tmp повторяются 10 раз

In [66]:
array5 = repeat(tmp, 10)
println(array5)

[4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3]


##### 3.7) массив, в котором первый элемент массива tmp встречается 11 раз, второй элемент — 10 раз, третий элемент — 10 раз

In [67]:
array6 = vcat(fill(tmp[1], 11), fill(tmp[2], 10), fill(tmp[3], 10))
println(array6)

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]


##### 3.8) массив, в котором первый элемент массива tmp встречается 10 раз подряд, второй элемент — 20 раз подряд, третий элемент — 30 раз подряд

In [68]:
array7 = vcat(fill(tmp[1], 10), fill(tmp[2], 20), fill(tmp[3], 30))
println(array7)

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]


##### 3.9) массив из элементов вида 2^𝑡𝑚𝑝[𝑖], 𝑖 = 1, 2, 3, где элемент 2^𝑡𝑚𝑝[3] встречается 4 раза; посчитайте в полученном векторе, сколько раз встречается цифра 6, и выведите это значение на экран

In [69]:
# Задаем массив tmp
tmp = [4, 6, 3]

# Формируем массив: элемент 2^tmp[3] повторяется 4 раза
result_array = [2^tmp[i] for i in 1:3]
result_array = vcat(result_array, repeat([2^tmp[3]], 4))

# Преобразуем массив в строку для поиска цифры '6'
result_string = join(result_array, "")
count_6 = count(x -> x == '6', result_string)

# Выводим массив и количество цифр 6
println("Результирующий массив: ", result_array)
println("Количество цифры 6: ", count_6)

Результирующий массив: [16, 64, 8, 8, 8, 8, 8]
Количество цифры 6: 2


##### 3.10) вектор значений 𝑦 = 𝑒^𝑥 cos(𝑥) в точках 𝑥 = 3, 3.1, 3.2, … , 6, найдите среднее значение 𝑦

In [70]:
using Statistics

x = 3:0.1:6
y = [exp(x) * cos(x) for x in x]

println("Среднее значение y: ", mean(y))

Среднее значение y: 53.11374594642971


##### 3.11) вектор вида (𝑥^𝑖, 𝑦^𝑗), 𝑥 = 0.1, 𝑖 = 3, 6, 9, … , 36, 𝑦 = 0.2, 𝑗 = 1, 4, 7, … , 34

In [71]:
xi = collect(3:3:36) * 0.1
yj = collect(1:3:34) * 0.2
vector11 = [(x, y) for x in xi, y in yj]
println(vector11)

[(0.30000000000000004, 0.2) (0.30000000000000004, 0.8) (0.30000000000000004, 1.4000000000000001) (0.30000000000000004, 2.0) (0.30000000000000004, 2.6) (0.30000000000000004, 3.2) (0.30000000000000004, 3.8000000000000003) (0.30000000000000004, 4.4) (0.30000000000000004, 5.0) (0.30000000000000004, 5.6000000000000005) (0.30000000000000004, 6.2) (0.30000000000000004, 6.800000000000001); (0.6000000000000001, 0.2) (0.6000000000000001, 0.8) (0.6000000000000001, 1.4000000000000001) (0.6000000000000001, 2.0) (0.6000000000000001, 2.6) (0.6000000000000001, 3.2) (0.6000000000000001, 3.8000000000000003) (0.6000000000000001, 4.4) (0.6000000000000001, 5.0) (0.6000000000000001, 5.6000000000000005) (0.6000000000000001, 6.2) (0.6000000000000001, 6.800000000000001); (0.9, 0.2) (0.9, 0.8) (0.9, 1.4000000000000001) (0.9, 2.0) (0.9, 2.6) (0.9, 3.2) (0.9, 3.8000000000000003) (0.9, 4.4) (0.9, 5.0) (0.9, 5.6000000000000005) (0.9, 6.2) (0.9, 6.800000000000001); (1.2000000000000002, 0.2) (1.2000000000000002, 0.8)

##### 3.12) вектор с элементами (2^𝑖)/𝑖, 𝑖 = 1, 2, … , 𝑀, 𝑀 = 25


In [72]:
M = 25
vector12 = [2^i / i for i in 1:M]
println(vector12)

[2.0, 2.0, 2.6666666666666665, 4.0, 6.4, 10.666666666666666, 18.285714285714285, 32.0, 56.888888888888886, 102.4, 186.1818181818182, 341.3333333333333, 630.1538461538462, 1170.2857142857142, 2184.5333333333333, 4096.0, 7710.117647058823, 14563.555555555555, 27594.105263157893, 52428.8, 99864.38095238095, 190650.18181818182, 364722.0869565217, 699050.6666666666, 1.34217728e6]


##### 3.13) вектор вида (”fn1”, ”fn2”, …, ”fnN”), 𝑁 = 30

In [73]:
N = 30
vector13 = ["fn$i" for i in 1:N]
println(vector13)

["fn1", "fn2", "fn3", "fn4", "fn5", "fn6", "fn7", "fn8", "fn9", "fn10", "fn11", "fn12", "fn13", "fn14", "fn15", "fn16", "fn17", "fn18", "fn19", "fn20", "fn21", "fn22", "fn23", "fn24", "fn25", "fn26", "fn27", "fn28", "fn29", "fn30"]


##### 3.14) векторы 𝑥 = (𝑥1, 𝑥2, … , 𝑥𝑛) и 𝑦 = (𝑦1, 𝑦2, … , 𝑦𝑛) целочисленного типа длины 𝑛 = 250 как случайные выборки из совокупности 0, 1, …, 999; на его основе:

In [74]:
using Random

x = rand(0:999, 250)
y = rand(0:999, 250)

# Выбор y > 600
filtered_y = y[y .> 600]
println("Элементы y > 600: ", filtered_y)

# Соответствующие элементы x
corresponding_x = x[findall(y .> 600)]
println("Соответствующие x: ", corresponding_x)

# Различные операции
sum_exp = sum(exp.(-x[2:end] + x[1:end-1]) .+ 10)
println("Сумма: ", sum_exp)

# Уникальные элементы x
unique_x = unique(x)
println("Уникальные элементы x: ", unique_x)

Элементы y > 600: [978, 725, 824, 778, 766, 702, 659, 981, 707, 844, 731, 725, 823, 752, 781, 637, 793, 817, 688, 870, 950, 980, 986, 745, 650, 677, 718, 709, 635, 937, 781, 601, 862, 862, 933, 737, 711, 703, 947, 625, 791, 856, 808, 860, 737, 984, 811, 912, 733, 823, 829, 697, 845, 709, 953, 738, 730, 732, 876, 814, 827, 915, 853, 734, 765, 946, 829, 749, 873, 746, 801, 634, 866, 829, 702, 801, 948, 750, 637, 777, 846, 982, 704, 839, 608, 612, 992, 757, 789, 761, 947, 703, 941, 718, 928, 732, 951, 949, 859, 608, 870, 653]
Соответствующие x: [724, 841, 127, 610, 632, 645, 844, 753, 576, 236, 760, 416, 286, 225, 28, 579, 869, 239, 184, 790, 561, 997, 748, 157, 431, 881, 678, 667, 114, 576, 947, 799, 690, 660, 325, 800, 913, 648, 382, 296, 551, 406, 343, 397, 153, 902, 280, 652, 18, 210, 288, 589, 941, 355, 575, 675, 931, 793, 335, 367, 989, 376, 581, 876, 33, 412, 276, 216, 617, 300, 778, 466, 854, 5, 117, 230, 335, 726, 667, 119, 600, 187, 758, 191, 602, 529, 223, 685, 399, 751, 771, 2

#### №4. Создайте массив squares, в котором будут храниться квадраты всех целых чисел от 1 до 100.

In [75]:
squares = [i^2 for i in 1:100]
println(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000]


#### 5. Подключите пакет Primes (функции для вычисления простых чисел). Сгенерируйте массив myprimes, в котором будут храниться первые 168 простых чисел. Определите 89-е наименьшее простое число. Получите срез массива с 89-го до 99-го элемента включительно, содержащий наименьшие простые числа.

In [81]:
import Pkg; Pkg.add("Primes")

    Updating registry at `C:\Users\legion\.julia\registries\General.toml`
   Resolving package versions...
   Installed Primes ─────────── v0.5.6
   Installed IntegerMathUtils ─ v0.1.2
    Updating `C:\Users\legion\.julia\environments\v1.11\Project.toml`
  [27ebfcd6] + Primes v0.5.6
    Updating `C:\Users\legion\.julia\environments\v1.11\Manifest.toml`
  [18e54dd8] + IntegerMathUtils v0.1.2
  [27ebfcd6] + Primes v0.5.6
Precompiling project...
    583.2 ms  ✓ IntegerMathUtils
    611.9 ms  ✓ Primes
  2 dependencies successfully precompiled in 2 seconds. 43 already precompiled.


In [83]:
using Primes

# Создаем список простых чисел до 1000 (или другого достаточно большого числа)
myprimes = primes(1000)

println("89-е простое число: ", myprimes[89])
println("Срез: ", myprimes[89:99])

89-е простое число: 461
Срез: [461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523]


#### 6. Вычислите выражения:

##### 6.1

In [84]:
sum1 = sum(i^3 + 4*i^2 for i in 10:100)
println(sum1)

26852735


##### 6.2

In [85]:
sum2 = sum((2^i / i + 3^i / i^2) for i in 1:25)
println(sum2)

2.1291704368143802e9


##### 6.3

In [86]:
sum3 = sum(prod(2:2n) / prod(3:2n+1) for n in 1:19)
println(sum3)

12.84175745993532
